name:                hpsched
version:             0.1.0.0
github:              "brenoafb/hpsch"
license:             BSD3
author:              "brenoafb"
maintainer:          "brenoafb@gmail.com"
copyright:           "2020 Breno Fatureto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/brenoafb/hpsch#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time
- haskeline
- mtl
- aeson
- aeson-pretty
- bytestring
- containers
- directory

library:
  source-dirs: src

executables:
  hpsched-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpsched

tests:
  hpsched-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpsched
